apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-hello-kubernetes-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-hello-kubernetes
    spec:
      containers:
      - name: flask-hello-kubernetes
        image: dockerbogo/flask-hello-kubernetes:2.0.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 5000

